### ISSUE TITLE
Memoty leak in yandex.music

### ISSUE THREAD

**Issue by asm0dey** [dandygithub/kodi#36]
During playback of playlist I've encoutered restart of Kodi with following error

```
2020-05-12 12:55:29.784 T:139865488377600 WARNING: CPythonInvoker(31, /home/xbmc/.kodi/addons/plugin.audio.music.yandex/default.py): the python script "/home/xbmc/.kodi/addons/plugin.audio.music.yandex/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2020-05-12 12:55:36.417 T:139865413281536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'src'
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/plugin.audio.music.yandex/default.py", line 273, in <module>
                                                plugin.main()
                                              File "/home/xbmc/.kodi/addons/plugin.audio.music.yandex/default.py", line 143, in main
                                                return method(**params)
                                              File "/home/xbmc/.kodi/addons/plugin.audio.music.yandex/default.py", line 241, in play
                                                item = xbmcgui.ListItem(path=track.mp3)
                                              File "/home/xbmc/.kodi/addons/plugin.audio.music.yandex/api.py", line 233, in mp3
                                                response = requests.get(self.body['src'])
                                            KeyError: 'src'
                                            -->End of Python script error report<--

```

Kodi Leia latest

**Comment by DesSolo** [comment]
A memory leak error - is a possible but not required condition.
All kodi exceptions mention this
