### ISSUE TITLE
hdrezka.tv: the first video on the list does not play

### ISSUE THREAD

**Issue by LmarLoe** [dandygithub/kodi#77]
In many series the first episode on the list refuses to play

```
2022-04-19 11:14:23.848 T:1734435712   DEBUG: CAddonSettings[plugin.video.hdrezka.tv]: loading setting definitions
2022-04-19 11:14:23.848 T:1734435712   DEBUG: CAddonSettings[plugin.video.hdrezka.tv]: trying to load setting definitions from old format...
2022-04-19 11:14:23.850 T:1734435712   DEBUG: CAddonSettings[plugin.video.hdrezka.tv]: loading setting values
2022-04-19 11:14:23.851 T:1734435712  NOTICE: hdrezka: *** play_episode
2022-04-19 11:14:23.855 T:1734435712  NOTICE: hdrezka: *** get_links
2022-04-19 11:14:23.856 T:1734435712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.hdrezka.tv/default.py", line 434, in <module>
                                                plugin.main()
                                              File "/storage/.kodi/addons/plugin.video.hdrezka.tv/default.py", line 70, in main
                                                urllib.unquote_plus(params['data'])
                                              File "/storage/.kodi/addons/plugin.video.hdrezka.tv/default.py", line 423, in play_episode
                                                links = self.get_links(self.decode_response(data))
                                              File "/storage/.kodi/addons/plugin.video.hdrezka.tv/default.py", line 307, in get_links
                                                manifest_links[int(link.split("]")[0].replace("[", "").replace("p", ""))] = link.split("]")[1]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2022-04-19 11:14:23.856 T:1734435712   DEBUG: onExecutionDone(30, /storage/.kodi/addons/plugin.video.hdrezka.tv/default.py)
2022-04-19 11:14:23.911 T:1937159232   DEBUG: ------ Window Init (DialogNotification.xml) ------
2022-04-19 11:14:23.994 T:1734435712    INFO: Python interpreter stopped
2022-04-19 11:14:23.994 T:1734435712   DEBUG: Thread LanguageInvoker 1734435712 terminating
2022-04-19 11:14:23.995 T:1937159232   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2022-04-19 11:14:23.995 T:1534055296   DEBUG: Thread scriptobs 1534055296 terminating
2022-04-19 11:14:23.996 T:1937159232   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.hdrezka.tv/?mode=play_episode&url=https://rezka.ag/series/drama/7769-luchshe-zvonite-solu-2015.html&urlm=https://rezka.ag/series/drama/7769-luchshe-zvonite-solu-2015.html&post_id=7769&season_id=6&episode_id=1&title=Лучше звоните Солу (S6E1)&image=https://static.hdrezka.ac/i/2022/3/11/d9770106ba525pl95d16v.jpg&idt=35&data=#hWzM2MHBdaHR0cHM6Ly9zdHJlYW0udm9pZGJvb3N0LmNjLzUvNC8xLzcvOC8wLzBjNDM4ZDhkM2NkNzlkZWEwZWJiOTdiODM3Mzk1YTk5OjIwMjIwNDIwMDc6VXpCdFpVZGtkM2wyWVVsRk4waDZNMUF4VUZSWFVsWnVjbk5qWTJ0Qk5IaEhWMlE0TkRSclZDczFTMWRWYUcwNE1reENOemxRZDBsUFZUYzJVMW8yWVZCb1JHWk9jVU5ESzB4NU9YUk1jME5NV2trcllYYzlQUT09L2N0bGMzLm1wNDpobHM6bWFuaWZlc3QubTN1OCBvciBodHRwczovL3N0cmVhbS52b2lkYm9vc3QuY2MvOWFhYTZiYWM3MTcyNjM2YTkwMjFlY2RiZDg4ODE5MDk6MjAyMjA0MjAwNzpVekJ0WlVka2QzbDJZVWxGTjBoNk0xQXhVRlJYVWxadWNuTmpZMnRCTkhoSFYyUTRORFJyVkNzMVMxZFZhRzA0TWt4Q056bFFkMGxQVlRjMlUxbzJZVkJvUkdaT2NVTkRLMHg1T1hSTWMwTk1Xa2tyWVhjOVBRPT0vNS80LzEvNy84LzAvY3RsYzMubXA0LFs0ODBwXWh0dHBzOi8vc3RyZWFtLnZvaWRib29zdC5jYy81L//_//JCQjISFAIyFAIyM=zQvMS83LzgvMC8wYzQzOGQ4ZDNjZDc5ZGVhMGViYjk3YjgzNzM5NWE5OTo//_//Xl5eIUAjIyEhIyM=yMDIyMDQyMDA3OlV6QnRaVWRrZDNsMllVbEZOMGg2TTFBeFVGUlhVbFp1Y25OalkydEJOSGhIVjJRNE5EUnJWQ3MxUzFkVmFHMDRNa3hDTnpsUWQwbFBWVGMyVTFvMllWQm9SR1pPY1VOREsweDVPWFJNYzBOTVdra3JZWGM5UFE9PS96MXhlaC5tcDQ6aGxzOm1hbmlmZXN0Lm0zdTggb3IgaHR0cHM6Ly9zdHJlYW0udm9pZGJvb3N0LmNjL2ExYzZlODA3Njg5OTgwYjE0NzIwZWZkZjNmM2Q2NmRjOjIwMjIwNDIwMDc6VXpCdFpVZGtkM2wyWVVsRk4waDZNMUF4VUZSWFVsWnVjbk5qWTJ0Qk5IaEhWMlE0TkRSclZDczFTMWRWYUcwNE1reENOemxRZDBsUFZUYzJVMW8yWVZCb1JHWk9jVU5ESzB4NU9YUk1jME5NV2trcllYYzlQUT09LzUvNC8xLzcvOC8wL3oxeGVoLm1wNCxbNzIwcF1odHRwczovL3N0cmVhbS52b2lkYm9vc3QuY2MvNS80LzEvNy84LzAvMGM0MzhkOGQzY2Q3OWRlYTBlYmI5N2I4MzczOTVhOTk6MjAyMjA0MjAwNzpVekJ0WlVka2QzbDJZVWxGTjBoNk0xQXhVRlJYVWxadWNuTmpZMnRCTkhoSFYyUTRORFJyVkNzMVMxZFZhRzA0TWt4Q056bFFkMGxQVlRjMlUxbzJZVkJvUkdaT2NVTkRLMHg1T1hSTWMwTk1Xa2tyWVhjOVBRPT0vMWZ1ZzYubXA0OmhsczptYW5pZmVzdC5tM3U4IG9yIGh0dHBzOi8vc3RyZWFtLnZvaWRib29zdC5jYy8xMmNkMDE4MWZmZDZkMWYzNjE4ZjQyZjdkNWE0ZjlhZDoyMDIyMDQyMDA3OlV6QnRaVWRrZDNsMllVbEZOMGg2TTFBeFVGUlhVbFp1Y25OalkydEJOSGhIVjJRNE5EUnJWQ3MxUzFkVmFHMDRNa3hDTnpsUWQwbFBWVGMyVTFvMllWQm9SR1pPY1VOREsweDVPWFJNYzBOTVdra3JZWGM5UFE9PS81LzQvMS83Lzg//_//QEBAQEAhIyMhXl5evMC8xZnVnNi5tcDQsWzEwODBwXWh0dHBzOi8vc3RyZWFtLnZvaWRib29zdC5jYy81LzQvMS83LzgvMC8wYzQzOGQ4ZDNjZDc5ZGVhMGViYjk3YjgzNzM5NWE5OToyMDIyMDQyMDA3OlV6QnRaVWRrZDNsMllVbEZOMGg2TTFBeFVGUlhVbFp1Y25OalkydEJOSGhIVjJRNE5EUnJWQ3MxUzFkVmFHMDRNa3hDTnpsUWQwbFBWVGMyVTFvMllWQm9SR1pPY1VOREsweDVPWFJNYzBOTVdra3JZWGM5UFE9PS9pYnhqcS5tcDQ6aGxzOm1hbmlmZXN0Lm0zdTggb3IgaHR0cHM6Ly9zdHJlYW0udm9pZGJvb3N0LmNjL2JkNjE3M2M2MDhjMGJhOGIwMzExZjJlMTljYmIzM2UyOjIwMjIwNDIwMDc6VXpCdFpVZGtkM2wyWVVsRk4waDZNMUF4VUZSWFVsWnVjbk5qWTJ0Qk5IaEhWMlE0TkRSclZDczFTMWRWYUcwNE1reENOemxRZDBsUFZUYzJVMW8yWVZCb1JHWk9jVU5ESz//_//IyMjI14hISMjIUBAB4NU9YUk1jME5NV2trcllYYzlQUT09LzUvNC8xLzcvOC8wL2lieGpxLm1wNCxbMTA4MHAgVWx0cmFdaHR0cHM6Ly9zdHJlYW0udm9pZGJvb3N0LmNjLzUvNC8xLzcvOC8wLzBjNDM4ZDhkM2NkNzlkZWEwZWJiOTdiODM3Mzk1YTk5OjIwMjIwNDIwMDc6VXpCdFpVZGtkM2wyWVVsRk4waDZNMUF4VUZSWFVsWnVjbk5qWTJ0Qk5IaEhWMlE0TkRSclZDczFTMWRWYUcwNE1reENOemxRZDBsUFZUYzJVMW8yWVZCb1JHWk9jVU5ESzB4NU9YUk1jME5NV2trcllYYzlQUT09L3piemJrLm1wNDpobHM6bWFuaWZlc3QubTN1OCBvciBodHRwczovL3N0cmVhbS52b2lkYm9vc3QuY2MvYjhhYmM0YWM2MDgwZjRlNDhhZTM2ODI2YTBkYTY0NWU6MjAyMjA0MjAwNzpVekJ0WlVka2QzbDJZVWxGTjBoNk0xQXhVRlJYVWxadWNuTmpZMnRCTkhoSFYyUTRORFJyVkNzMVMxZF//_//JCQhIUAkJEBeIUAjJCRAZhRzA0TWt4Q056bFFkMGxQVlRjMlUxbzJZVkJvUkdaT2NVTkRLMHg1T1hSTWMwTk1Xa2tyWVhjOVBRPT0vNS80LzEvNy84LzAvemJ6YmsubXA0]
2022-04-19 11:14:23.997 T:1937159232   DEBUG: Playlist Player: one or more items failed to play... aborting playback
```

**Comment by LmarLoe** [comment]
Fixed in 2.5.10.  ✅
