### ISSUE TITLE
Error while series episode play

### ISSUE THREAD

**Issue by kaustas** [dandygithub/kodi#84]
2022-12-12 23:45:21.763 T:2380     INFO <general>: Python interpreter stopped
2022-12-12 23:45:21.777 T:5020    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://[plugin.video.hdrezka.tv/?mode=play_episode&url=%2Fseries%2Fcrime%2F1888-klan-soprano-1999.html&urlm=%2Fseries%2Fcrime%2F1888-klan-soprano-1999.html&post_id=1888&season_id=3&episode_id=7&title=%D0%A1%D0%B5%D1%80%D0%B8%D1%8F+7+%28%D0%A1%D0%B5%D0%B7%D0%BE%D0%BD+3%29&image=http%3A%2F%2Fstatic.rezka.cloud%2Fi%2F2020%2F12%2F26%2Fe2ad0777256c2lz63z80x.jpeg&idt=80](http://plugin.video.hdrezka.tv/?mode=play_episode&url=%2Fseries%2Fcrime%2F1888-klan-soprano-1999.html&urlm=%2Fseries%2Fcrime%2F1888-klan-soprano-1999.html&post_id=1888&season_id=3&episode_id=7&title=%D0%A1%D0%B5%D1%80%D0%B8%D1%8F+7+%28%D0%A1%D0%B5%D0%B7%D0%BE%D0%BD+3%29&image=http%3A%2F%2Fstatic.rezka.cloud%2Fi%2F2020%2F12%2F26%2Fe2ad0777256c2lz63z80x.jpeg&idt=80)]
2022-12-12 23:45:23.241 T:8216     INFO <general>: initializing python engine.
2022-12-12 23:45:23.575 T:8216     INFO <general>: hdrezka: *** main params: {'mode': 'play_episode', 'url': '/series/crime/1888-klan-soprano-1999.html', 'urlm': '/series/crime/1888-klan-soprano-1999.html', 'post_id': '1888', 'season_id': '3', 'episode_id': '7', 'title': 'Серия 7 (Сезон 3)', 'image': 'http://static.rezka.cloud/i/2020/12/26/e2ad0777256c2lz63z80x.jpeg', 'idt': '80'}
2022-12-12 23:45:23.926 T:8216    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'bool' object has no attribute 'replace'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\[plugin.video.hdrezka.tv](http://plugin.video.hdrezka.tv/)\default.py", line 570, in <module>
                                                       plugin.main()
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\[plugin.video.hdrezka.tv](http://plugin.video.hdrezka.tv/)\default.py", line 84, in main
                                                       self.play_episode(
 
                                                    File "C:\Users\User\AppData\Roaming\Kodi\addons\[plugin.video.hdrezka.tv](http://plugin.video.hdrezka.tv/)\default.py", line 558, in play_episode
                                                       links = parse_streams(data)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\[plugin.video.hdrezka.tv](http://plugin.video.hdrezka.tv/)\voidboost.py", line 16, in parse_streams
                                                       salted = salted.replace('\\', '')
                                                   AttributeError: 'bool' object has no attribute 'replace'
                                                   -->End of Python script error report<--

**Comment by kaustas** [comment]
content not allowed in region
