### ISSUE TITLE
HDRezka add-on failing to load movie lists

### ISSUE THREAD

**Issue by mpashkovskiy** [dandygithub/kodi#93]
```log
2024-02-14 19:55:31.580 T:16209   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/plugin.video.hdrezka.tv/default.py", line 579, in <module>
                                                       plugin.main()
                                                     File "/home/pi/.kodi/addons/plugin.video.hdrezka.tv/default.py", line 96, in main
                                                       self.index(params.get('uri'), params.get('page'), params.get('query_filter'))
                                                     File "/home/pi/.kodi/addons/plugin.video.hdrezka.tv/default.py", line 230, in index
                                                       info = self.get_item_additional_info(post_ids[i])
                                                     File "/home/pi/.kodi/addons/plugin.video.hdrezka.tv/default.py", line 435, in get_item_additional_info
                                                       additional['description'] = common.parseDOM(response.text, 'div', attrs={'class': 'b-content__bubble_text'})[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2024-02-14 19:55:31.581 T:16209   DEBUG <general>: onExecutionDone(84, /home/pi/.kodi/addons/plugin.video.hdrezka.tv/default.py)
2024-02-14 19:55:31.589 T:1525    DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2024-02-14 19:55:31.673 T:16209   DEBUG <general>: .
2024-02-14 19:55:31.960 T:16209    INFO <general>: Python interpreter stopped
2024-02-14 19:55:31.960 T:16209   DEBUG <general>: Thread LanguageInvoker 1180342848 terminating
2024-02-14 19:55:31.979 T:16207   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.hdrezka.tv/?mode=index
2024-02-14 19:55:31.980 T:16207   DEBUG <general>: Thread waiting 1241508416 terminating
2024-02-14 19:55:31.987 T:1525    DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
```

**Comment by mvrk69** [comment]
I tried today and same problem.

**Comment by Zeltorix** [comment]
fix
`
try:
    additional['description'] = common.parseDOM(response.text, 'div', attrs={'class': 'b-content__bubble_text'})[0]
except IndexError:
    log(f'fault parse description: {post_id}')
`

**Comment by mvrk69** [comment]
Thank you, works fine with that fix.

**Comment by dandygithub** [comment]
fix
